algorithm: fixmatch
save_dir: ./saved_models/fixmatch/
save_name: fixmatch_cbcnet_1
net: CBCNet
use_pretrain: True
pretrain_path: /data/code/Semi-supervised-learning/semilearn/nets/cbc/cbcnet_pretrain230315.pth
resume: False,
load_path: ./saved_models/fixmatch/freematch_cbcnet_1/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 200
num_train_iter: 4480200
num_log_iter: 22401
num_eval_iter: 200
batch_size: 8
eval_batch_size: 8
num_labels: 179212
num_warmup_iter: 22401
#num_labels: 400
uratio: 1
ema_m: 0.0
hard_label: True
T: 0.5
p_cutoff: 0.95
ulb_loss_ratio: 1.0
ema_p: 0.999
ent_loss_ratio: 0.001
img_size: 32
crop_ratio: 0.875
optim: AdamW
lr: 0.0005
layer_decay: 0.5
momentum: 0.9
weight_decay: 0.0005
amp: True
clip: 0.0
use_cat: True
net_from_name: False
data_dir: /data2/fssd2/damagou_error
dataset: cbcnet
train_sampler: RandomSampler
num_classes: 4363
num_workers: 4
seed: 0
world_size: 1
rank: 0
#distributed: False
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10081
dist_backend: nccl
gpu: None

