algorithm: softmatch
save_dir: ./saved_models/usb_cv/
save_name: softmatch_cbcnet_200_0
resume: False
load_path: ./saved_models/usb_cv/softmatch_cbcnet_50_0/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 200
num_train_iter: 1132200
num_log_iter: 200
num_eval_iter: 5661
batch_size: 256
eval_batch_size: 256
num_warmup_iter: 5661
#num_labels: 200
uratio: 1
ema_m: 0.0
hard_label: True
T: 0.5
dist_align: True
dist_uniform: True
per_class: False
ema_p: 0.999
ulb_loss_ratio: 1.0
n_sigma: 2
img_size: 32
crop_ratio: 0.95
optim: AdamW
lr: 0.0001
layer_decay: 0.5
momentum: 0.9
weight_decay: 0.0005
amp: False
clip: 0.0
use_cat: True
net: CBCNet
net_from_name: False
data_dir: /data2/fssd2/damagou_error
dataset: cbcnet
train_sampler: RandomSampler
num_classes: 4410
num_workers: 8
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10086
dist_backend: nccl
gpu: None
use_pretrain: True
pretrain_path: /data/code/Semi-supervised-learning/semilearn/nets/cbc/cbcnet_pretrain230315.pth
